
on:
  workflow_dispatch:
    inputs:
      link:
        description: "Youtube video link"
        required: true
        default: "https://www.youtube.com/watch?v=sgr92n5EGyo"
name: Get Subs
jobs:
  get:
    name: Get Subs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: npm i
      - run: node dist/cli.js $link > subs.json
        env:
          link: ${{ github.event.inputs.link }}
      - uses: actions/upload-artifact@v2
        with:
          name: subs.json
          path: subs.json
